### PR TITLE
Add Pagination to search

### PR DESCRIPTION
**Pull request by TreeN0de**
This should implement the feature requested in #214.
Therefor I added a new parameter ` function_name ` to Pagination. ` function_name` stores the target function name. I also I renamed the parameter `filter` to `params`.

### CODE REVIEW

**Comment by w3ich3rt** [comment]
I would love this feature

**Comment by joeirimpan** [comment]
Thanks for this PR. Can you run black linter on this once? LFTM otherwise.

**Comment by Anuril** [comment]
LGTM too. Interesting solution re: function_name. Might need to change that in some other places too.

**Comment by TreeN0de** [comment]
This solution is just a quick fix. I think this could also be done by creating some subclasses of Pagination. But that is a matter of taste.
I didn't find `black` in the `CONTRIBUTING.rst`, so I checked the logs. I hope I used the right one. Perhaps `black` should be added to the `CONTRIBUTING.rst`.

**Review by joeirimpan — APPROVED** [review]

**Pull request merged**
